
#ifndef _DT_BINDINGS_ALLWINNER_H6_GPIO_H
#define _DT_BINDINGS_ALLWINNER_H6_GPIO_H

#include <dt-bindings/gpio/gpio.h>

#define  ALLWINNER_H6_GPIOC_NUMBER     17
#define  ALLWINNER_H6_GPIOD_NUMBER     27
#define  ALLWINNER_H6_GPIOF_NUMBER     7
#define  ALLWINNER_H6_GPIOG_NUMBER     15
#define  ALLWINNER_H6_GPIOH_NUMBER     11
#define  ALLWINNER_H6_GPIOL_NUMBER     11
#define  ALLWINNER_H6_GPIOM_NUMBER     5


#define  ALLWINNER_H6_GPIO_PORT_C    0
#define  ALLWINNER_H6_GPIO_PORT_D    1
#define  ALLWINNER_H6_GPIO_PORT_F    2
#define  ALLWINNER_H6_GPIO_PORT_G    3
#define  ALLWINNER_H6_GPIO_PORT_H    4
#define  ALLWINNER_H6_GPIO_PORT_L    5
#define  ALLWINNER_H6_GPIO_PORT_M    6
#define  ALLWINNER_H6_MAX_GPIO       ALLWINNER_H6_GPIO_PORT_M




#endif



