
#ifndef  __GPIO_ALLWINNER_H6_H_
#define  __GPIO_ALLWINNER_H6_H_


typedef enum  {
	ALLWINNER_H6_GPIO_DRV_LEVEL0 = 0,
	ALLWINNER_H6_GPIO_DRV_LEVEL1,
    ALLWINNER_H6_GPIO_DRV_LEVEL2,
    ALLWINNER_H6_GPIO_DRV_LEVEL3,
    ALLWINNER_H6_GPIO_DRV_MAX = ALLWINNER_H6_GPIO_DRV_LEVEL3,
} allwinner_h6_gpio_drv_mode_e;


typedef enum {
	ALLWINNER_H6_GPIO_PUPD_NO = 0,
	ALLWINNER_H6_GPIO_PUPD_UP,
	ALLWINNER_H6_GPIO_PUPD_DOWN,
    ALLWINNER_H6_GPIO_MAX = ALLWINNER_H6_GPIO_PUPD_DOWN
} allwinner_h6_gpio_pupd_e;


// typedef enum {
// 	ALLWINNER_H6_GPIO_AF0 = 0,
// 	ALLWINNER_H6_GPIO_AF1,
// 	ALLWINNER_H6_GPIO_AF2,
// 	ALLWINNER_H6_GPIO_AF3,
// 	ALLWINNER_H6_GPIO_AF4,
// 	ALLWINNER_H6_GPIO_AF5,
// 	ALLWINNER_H6_GPIO_AF6,
// 	ALLWINNER_H6_GPIO_AF7,
// 	ALLWINNER_H6_GPIO_MAX_AF  =  ALLWINNER_H6_GPIO_AF7
// } allwinner_h6_gpio_af_e;




// #define  ALLWINNER_H6_GPIO_INPUT       ALLWINNER_H6_GPIO_AF0
// #define  ALLWINNER_H6_GPIO_OUTPUT      ALLWINNER_H6_GPIO_AF1
// #define  ALLWINNER_H6_GPIO_DISABLE     ALLWINNER_H6_GPIO_AF7

#define  ALLWINNER_H6_GPIO_MAX_PIN         31











#endif


